
let hello = "hello";
let owu = "owu";
let com = "com";
let ua = "ua";
let num1 = 1;
let num2 = 10;
let num3 = -999;
let num4 = 123;
let num5 = 3.14;
let num6 = 2.7;
let num7 = 16;
let isTrue = true;
let isFalse = false;
console.log(hello);
console.log(owu);
console.log(com);
console.log(ua);
console.log(num1);
console.log(num2);
console.log(num3);
console.log(num4);
console.log(num5);
console.log(num6);
console.log(num7);
console.log(isTrue);
console.log(isFalse);
alert(hello);
alert(owu);
alert(com);
alert(ua);
alert(num1);
alert(num2);
alert(num3);
alert(num4);
alert(num5);
alert(num6);
alert(num7);
alert(isTrue);
alert(isFalse);
document.writeln(hello);
document.writeln(owu);
document.writeln(com);
document.writeln(ua);
document.writeln(num1);
document.writeln(num2);
document.writeln(num3);
document.writeln(num4);
document.writeln(num5);
document.writeln(num6);
document.writeln(num7);
document.writeln(isTrue);
document.writeln(isFalse);
hello = "Hi";
owu = "ok10";
com = "dot";
ua = "uk";
num1 = 5;
num2 = 50;
num3 = 999;
num4 = 321;
num5 = 3;
num6 = 2;
num7 = 32;
isTrue = false;
isFalse = true;
console.log(hello);
console.log(owu);
console.log(com);
console.log(ua);
console.log(num1);
console.log(num2);
console.log(num3);
console.log(num4);
console.log(num5);
console.log(num6);
console.log(num7);
console.log(isTrue);
console.log(isFalse);
alert(hello);
alert(owu);
alert(com);
alert(ua);
alert(num1);
alert(num2);
alert(num3);
alert(num4);
alert(num5);
alert(num6);
alert(num7);
alert(isTrue);
alert(isFalse);
document.writeln(hello);
document.writeln(owu);
document.writeln(com);
document.writeln(ua);
document.writeln(num1);
document.writeln(num2);
document.writeln(num3);
document.writeln(num4);
document.writeln(num5);
document.writeln(num6);
document.writeln(num7);
document.writeln(isTrue);
document.writeln(isFalse);

// Task3!!!
// let name = "Jack";
// let book = "White Fang";
// let lang = "English";
// let num1 = 1900;
// let num2 = 2000;
// let num3 = 2020;
// console.log(num1);
// console.log(num2);
// console.log(num3);
// console.log(name);
// console.log(book);
// console.log(lang);
// alert(num1);
// alert(num2);
// alert(num3);
// alert(name);
// alert(book);
// alert(lang);
// document.writeln(num1);
// document.writeln(num2);
// document.writeln(num3);
// document.writeln(name);
// document.writeln(book);
// document.writeln(lang);

// Task4-5-6!!!
// let firstName = prompt("Can you tell me your name?");
// let SurName = prompt("Can you tell me your surname, please?");
// let middleName = prompt ("Can you tell me your middle name, please?");
// console.log (firstName);
// console.log (middleName);
// console.log (SurName);
// alert (firstName);
// alert (middleName);
// alert (SurName);
// document.writeln (firstName);
// document.writeln (middleName);
// document.writeln (SurName);
// let Person = firstName + " " + middleName + " " + SurName;
// document.writeln (Person);
// let FatherfirstName = prompt("Can you tell me your father name?");
// let FatherSurName = prompt("Can you tell me your father surname, please?");
// let FathermiddleName = prompt ("Can you tell me your Father middle name, please?");
// console.log (FatherfirstName);
// console.log (FathermiddleName);
// console.log (FatherSurName);
// alert (FatherfirstName);
// alert (FathermiddleName);
// alert (FatherSurName);
// document.writeln (FatherfirstName);
// document.writeln (FathermiddleName);
// document.writeln (FatherSurName);
// let Father = FatherfirstName + " " + FathermiddleName + " " + FatherSurName;
// document.writeln (Father);
// let motherfirstName = prompt("Can you tell me your mother name?");
// let motherSurName = prompt("Can you tell me your mother surname, please?");
// let mothermiddleName = prompt ("Can you tell me your mother middle name, please?");
// console.log (motherfirstName);
// console.log (mothermiddleName);
// console.log (motherSurName);
// alert (motherfirstName);
// alert (mothermiddleName);
// alert (motherSurName);
// document.writeln (motherfirstName);
// document.writeln (mothermiddleName);
// document.writeln (motherSurName);
// let mother = firstName + " " + middleName + " " + SurName;
// document.writeln (mother);

// Task7!!!
// let num1 = +prompt("Tell me first number, please!");
// console.log(num1);
// let num2 = +prompt("Tell me second number, please");
// console.log(num2);
// let num3 = +prompt ("Tell me third number, please");
// console.log(num3);

// Task8!!!
// let num1 = parseInt(prompt ("Tell me first number, please"));
// let num2 = parseInt(prompt ("Tell me second number, please"));
// let num3 = parseInt(prompt ("Tell me third number, please"));
// let num4 = parseInt(prompt ("Tell me fourth number, please"));
// let result = num1 + num2 + num3 + num4;
// console.log (result);

// Task9!!!
// let num1 = parseFloat (prompt ("Tell me first float number, please"));
// let num2 = parseFloat (prompt ("Tell me second float number, please"));
// let num3 = parseFloat (prompt ("Tell me third float number, please"));
// let result = num1 + num2 + num3;
// console.log (result);

// Task10!!!
// let num1 = Math.round(parseFloat (prompt ("Tell me first float number, please"))) ;
// let num2 = Math.round(parseFloat (prompt ("Tell me second float number, please"))) ;
// let num3 = Math.round(parseFloat (prompt ("Tell me third float number, please")));
// let result = num1 + num2 + num3;
// console.log (result);

// Task11!!!
// let num1 = parseInt (prompt ("Tell me first number, please"));
// let num2 = parseInt (prompt ("Tell me second number, please"));
// let result = Math.pow(num1, num2);
// console.log (result);

// Task12!!!
// let a = 100;
// let b = "100";
// let c = true;
// let d = undefined;
// console.log(typeof a);
// console.log(typeof b);
// console.log(typeof c);
// console.log(typeof d);

// Task13!!!
// let one = 5<6;
// console.log(one);
// let two = 5>6;
// console.log(two);
// let three = 5>=6;
// console.log(three);
// let four = 5 == 6;
// console.log(four);
// let five = 10 == 10;
// console.log (five);
// let six = 10>=10;
// console.log (six);
// let seven = 10<10;
// console.log (seven);
// let eight = 10>10;
// console.log (eight);
// let nine = 10 != 10;
// console.log (nine);
// let ten = 123 ==="123";
// console.log (ten);
// let eleven = 123 === "123";
// console.log (eleven);

// Task14
// false console.log(132 > 100 && 45 < 12 );
// true console.log(34 > 33 && 23 < 90 );
// false console.log(99 > 100 && 45 > 12 );
// true console.log(132 > 100 || 45 < 12 );
// true console.log(111 > 11 || 45 < 111 );
// true console.log(111 > 11 || 45 < 111) && (132 > 100 || 45 < 12);
// true console.log((111 > 11 || 45 < 56) || (132 > 100 || 45 < 12) );
// false console.log((132 > 100 && 45 < 12 ) && (132 > 100 || 45 < 12 ) );
// true console.log((111 > 11 || 45 < 111) || (99 > 100 && 45 > 12 ));
// ? console.log(!!'-1');
// ? console.log(!!-1);
// ? console.log(!!'0');
// ? console.log(!!'null');
// ? console.log(!!'undefined');
// ? console.log(!!(3/'owu'));
// ? console.log((111 > 11 || 45 < 111) ||  !!'0');
// ? console.log((!!111 == !!11 || 45 < 111) && (99 > 100 && 45 > 12 ));


